version: '3.3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db:rw
    networks:
      - goal-net   
  backend:
    build: ./backend
    image: goal-node
    container_name: goal-backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/six
      - logs:/six/logs
    networks:
      - goal-net      

  frontend:
    container_name: goal-frontend
    build: ./frontend
    image: goal-react
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend
        
volumes:
  data:
  logs:
networks:
    goal-net:
      external: true
